# Generated by Django 5.1.5 on 2025-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('truck_type', models.CharField(choices=[('box', 'Box Truck'), ('flatbed', 'Flatbed'), ('reefer', 'Reefer'), ('van', 'Van'), ('other', 'Other')], max_length=20)),
                ('trailer_size', models.CharField(max_length=50)),
                ('mc_copy', models.FileField(upload_to='documents/mc/')),
                ('noa', models.FileField(upload_to='documents/noa/')),
                ('insurance_cert', models.FileField(upload_to='documents/insurance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
