# Generated by Django 5.1.5 on 2025-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='factoring_doc',
            field=models.FileField(default=1, upload_to='documents/factoring/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='other_truck_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
